package com.titiespada.onlinetestexammaker.model;
// Generated 5/jan/2018 22:51:25 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "question")
public class Question implements java.io.Serializable {

	private int id;
	private String title;
	private String problemDescription;
	private boolean haveMoreThanOneAnswer;
	private Set<QuestionChoiceAnswer> questionChoiceAnswers = new HashSet<QuestionChoiceAnswer>(0);
	private Set<QuestionTestExam> questionTestExams = new HashSet<QuestionTestExam>(0);

	public Question() {
	}

	public Question(int id, String title, String problemDescription, boolean haveMoreThanOneAnswer) {
		this.id = id;
		this.title = title;
		this.problemDescription = problemDescription;
		this.haveMoreThanOneAnswer = haveMoreThanOneAnswer;
	}

	public Question(int id, String title, String problemDescription, boolean haveMoreThanOneAnswer,
			Set<QuestionChoiceAnswer> questionChoiceAnswers, Set<QuestionTestExam> questionTestExams) {
		this.id = id;
		this.title = title;
		this.problemDescription = problemDescription;
		this.haveMoreThanOneAnswer = haveMoreThanOneAnswer;
		this.questionChoiceAnswers = questionChoiceAnswers;
		this.questionTestExams = questionTestExams;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "problem_description", nullable = false, length = 1000)
	public String getProblemDescription() {
		return this.problemDescription;
	}

	public void setProblemDescription(String problemDescription) {
		this.problemDescription = problemDescription;
	}

	@Column(name = "have_more_than_one_answer", nullable = false)
	public boolean isHaveMoreThanOneAnswer() {
		return this.haveMoreThanOneAnswer;
	}

	public void setHaveMoreThanOneAnswer(boolean haveMoreThanOneAnswer) {
		this.haveMoreThanOneAnswer = haveMoreThanOneAnswer;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "question")
	public Set<QuestionChoiceAnswer> getQuestionChoiceAnswers() {
		return this.questionChoiceAnswers;
	}

	public void setQuestionChoiceAnswers(Set<QuestionChoiceAnswer> questionChoiceAnswers) {
		this.questionChoiceAnswers = questionChoiceAnswers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "question")
	public Set<QuestionTestExam> getQuestionTestExams() {
		return this.questionTestExams;
	}

	public void setQuestionTestExams(Set<QuestionTestExam> questionTestExams) {
		this.questionTestExams = questionTestExams;
	}

}
