package com.titiespada.onlinetestexammaker.model;

// default package
// Generated 4/jan/2018 17:26:31 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QuestionChoiceAnswer generated by hbm2java
 */
@Entity
@Table(name = "question_choice_answer")
public class QuestionChoiceAnswer implements java.io.Serializable {

	private int id;
	private Question question;
	private String text;
	private String displayOrder;
	private boolean isCorrect;
	private Set users = new HashSet(0);

	public QuestionChoiceAnswer() {
	}

	public QuestionChoiceAnswer(int id, Question question, String text, String displayOrder, boolean isCorrect) {
		this.id = id;
		this.question = question;
		this.text = text;
		this.displayOrder = displayOrder;
		this.isCorrect = isCorrect;
	}

	public QuestionChoiceAnswer(int id, Question question, String text, String displayOrder, boolean isCorrect,
			Set users) {
		this.id = id;
		this.question = question;
		this.text = text;
		this.displayOrder = displayOrder;
		this.isCorrect = isCorrect;
		this.users = users;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "question_id", nullable = false)
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@Column(name = "text", nullable = false, length = 500)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "display_order", nullable = false, length = 500)
	public String getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(String displayOrder) {
		this.displayOrder = displayOrder;
	}

	@Column(name = "is_correct", nullable = false)
	public boolean isIsCorrect() {
		return this.isCorrect;
	}

	public void setIsCorrect(boolean isCorrect) {
		this.isCorrect = isCorrect;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "question_choice_answer_user", joinColumns = {
			@JoinColumn(name = "question_choice_answer_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "user_id", nullable = false, updatable = false) })
	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
