package com.titiespada.onlinetestexammaker.model;

// default package
// Generated 4/jan/2018 17:26:31 by Hibernate Tools 5.2.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TestExamUser generated by hbm2java
 */
@Entity
@Table(name = "test_exam_user")
public class TestExamUser implements java.io.Serializable {

	private TestExamUserId id;
	private TestExam testExam;
	private User user;
	private boolean hasFinish;

	public TestExamUser() {
	}

	public TestExamUser(TestExamUserId id, TestExam testExam, User user, boolean hasFinish) {
		this.id = id;
		this.testExam = testExam;
		this.user = user;
		this.hasFinish = hasFinish;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "testExamId", column = @Column(name = "test_exam_id", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)) })
	public TestExamUserId getId() {
		return this.id;
	}

	public void setId(TestExamUserId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "test_exam_id", nullable = false, insertable = false, updatable = false)
	public TestExam getTestExam() {
		return this.testExam;
	}

	public void setTestExam(TestExam testExam) {
		this.testExam = testExam;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "has_finish", nullable = false)
	public boolean isHasFinish() {
		return this.hasFinish;
	}

	public void setHasFinish(boolean hasFinish) {
		this.hasFinish = hasFinish;
	}

}
