package com.titiespada.onlinetestexammaker.model;

// default package
// Generated 4/jan/2018 17:26:31 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class User implements java.io.Serializable {

	private int id;
	private String fullName;
	private String username;
	private String password;
	private Set testExamUsers = new HashSet(0);
	private Set questionChoiceAnswers = new HashSet(0);

	public User() {
	}

	public User(int id, String fullName, String username, String password) {
		this.id = id;
		this.fullName = fullName;
		this.username = username;
		this.password = password;
	}

	public User(int id, String fullName, String username, String password, Set testExamUsers,
			Set questionChoiceAnswers) {
		this.id = id;
		this.fullName = fullName;
		this.username = username;
		this.password = password;
		this.testExamUsers = testExamUsers;
		this.questionChoiceAnswers = questionChoiceAnswers;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "full_name", nullable = false, length = 200)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "username", unique = true, nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set getTestExamUsers() {
		return this.testExamUsers;
	}

	public void setTestExamUsers(Set testExamUsers) {
		this.testExamUsers = testExamUsers;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "question_choice_answer_user", joinColumns = {
			@JoinColumn(name = "user_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "question_choice_answer_id", nullable = false, updatable = false) })
	public Set getQuestionChoiceAnswers() {
		return this.questionChoiceAnswers;
	}

	public void setQuestionChoiceAnswers(Set questionChoiceAnswers) {
		this.questionChoiceAnswers = questionChoiceAnswers;
	}

}
