package com.patriciaespada.onlinetestexammaker.model;
// Generated 5/jan/2018 22:51:25 by Hibernate Tools 5.2.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QuestionTestExam generated by hbm2java
 */
@Entity
@Table(name = "question_test_exam")
public class QuestionTestExam implements java.io.Serializable {

	private QuestionTestExamId id;
	private Question question;
	private TestExam testExam;
	private int order;

	public QuestionTestExam() {
	}

	public QuestionTestExam(QuestionTestExamId id, Question question, TestExam testExam, int order) {
		this.id = id;
		this.question = question;
		this.testExam = testExam;
		this.order = order;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "questionId", column = @Column(name = "question_id", nullable = false)),
			@AttributeOverride(name = "testExamId", column = @Column(name = "test_exam_id", nullable = false)) })
	public QuestionTestExamId getId() {
		return this.id;
	}

	public void setId(QuestionTestExamId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "question_id", nullable = false, insertable = false, updatable = false)
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "test_exam_id", nullable = false, insertable = false, updatable = false)
	public TestExam getTestExam() {
		return this.testExam;
	}

	public void setTestExam(TestExam testExam) {
		this.testExam = testExam;
	}

	@Column(name = "order", nullable = false)
	public int getOrder() {
		return this.order;
	}

	public void setOrder(int order) {
		this.order = order;
	}

}
